# Site
title:              Marthyn.nl
bio:                |
  My name is Marthyn Olthof and I am a software developer working at Hoppinger,
  doing freelance development work and open source stuff in Ruby, Rails, Javascript
  and aspiring to learn Prolog, Elixir, Haskell. Other than programming I love to watch sports,
  especially with engines! The topic's I write about vary from tech, cooking, comics, movies,
  sports and who knows whatever I'll find interesting!'
description:        "Marthyn Olthof, software developer, home cook, runner, motorsports fan"
reading_time:       true
words_per_minute:   150
logo:               'assets/img/logo.jpeg'
background:         'assets/img/placeholder-big.jpg'
tiled_bg:           false   # Set this true if you want to tile your background image, otherwise it will be covered
locale:             en_US
# url:                http://localhost:4000
url:                marthyn.github.io/

# Jekyll
permalink:          /:title/
markdown:           kramdown
highlighter:        rouge
kramdown:
  auto_ids:         true
  footnote_nr:      1
  entity_output:    as_char
  toc_levels:       1..6
  enable_coderay:   false
mathjax:            true
sass:
  sass_dir:         _sass
  style:            compressed

# Comments
disqus_shortname:   marthyngithubio

# Social
# if you don't have any of social below, comment the line.
google:
  #plus:            #username
  analytics:        7744761
  #verify:
  #ad-client:
  #ad-slot:
#bing-verify:
email:              Marthyn@live.nl
twitter:            Marthyn
facebook:           marthyn1337
github:             Marthyn
stackoverflow:      913824/marthyn-olthof
linkedin:           marthyn-olthof-14b72b31
#xing:              username
instagram:          marthyn__
lastfm:             marthijn1990
#tumblr:            username
#pinterest:         username
#foursquare:        username
# steam:              username
#dribbble:          username
#youtube:           username
#soundcloud:        username
#weibo:             username
#flickr:            username
#codepen:           username
#keybase:           username
#xmpp:              username@server.com
#hackernews:        username

# Gems
gems:
  - jekyll-mentions
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-gist

jekyll-mentions:
    base_url: https://github.com

# Exclude list
exclude: [README.md, Gemfile, Gemfile.lock, node_modules, gulpfile.js, package.json, _site, src, vendor, CNAME, LICENSE, Rakefile]
